name: Build macOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Install Tauri CLI
        run: yarn add -D @tauri-apps/cli

      - name: Build Tauri app
        run: yarn tauri build

      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app
          path: src-tauri/target/release/bundle/
